### ISSUE TITLE
Rozszerz store o kontakty i historię wiadomości

### ISSUE THREAD

**Issue by kacpak** [chat-sggw/app#12]

**Comment by kacpak** [comment]
@Sylwekqaz potrzebujemy struktury danych które dostaniemy z serwera by postawić wszystko po naszej stronie i chociaż zamockować interakcje które będziemy od Was dostawać
Kamil chce to zrobić jeszcze w tym roku
Jak to w tej chwili wygląda?

**Comment by yami12376** [comment]
Nie będzie info do czwartku włącznie - to nie robię tego - już z miesiąc czekam na info - wcześniej od Mateusza tygodniami

**Comment by Sylwekqaz** [comment]
Na branchu API_Mock jest już zamokowane API związane z userami i
friendsami, API związane z konwersacjami jest prawie skończone, pojawią się
małe poprawki. Więc możesz już zaczynać pracę.

Projekt musisz postawić lokalnie, nie wymaga żadnych dodatkowych
konfiguracji. Dokumentację API znajdziesz pod adresem /swagger/ui/index

W dniu wt., 2.01.2018 o 18:53 yami12376 <notifications@github.com>
napisał(a):

**Comment by kacpak** [comment]
#16
