### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by kacpak** [chat-sggw/app#8]
W tym issue należy wprowadzić również koncepcję routingu w aplikacji i jako domyślną stronę (przy braku kluczy w local storage) wyświetlić login page.

**Comment by kacpak** [comment]
Design będzie dostępny na dniach, ale możemy się już zająć logiką, by zacząć listę kontaktów

**Comment by DTJanicka** [comment]
Mamy już design, jak logika?

**Comment by SiwyDym** [comment]
Na branchu jest wersja testowa do sprawdzenia. Do Landing page dodany jest link do przekierowania do login page- do usuniecia tylko do testowania. Tj czysty front, bez logiki i wwalidacji.

**Comment by SiwyDym** [comment]
@kacpak Daj znać co powinienem poprawić lub czy mam pullnąć  req na mastera. Tak jak wczoraj rozmawialiśmy dodałem sam front bez logiki.

**Comment by kacpak** [comment]
daj PR od razu bo tak moge sie przyjrzec i zostawic komentarze

wt., 19 gru 2017 o 18:51 użytkownik SiwyDym <notifications@github.com>
napisał:
